on: 
  push:
    branches:
      - main

jobs:
  RSpec:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Setup Ruby and install gems'
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: 'Setup test database'
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:setup

      - name: 'Run tests'
        run: bundle exec rspec

  Linter:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Setup Ruby and install gems'
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: 'Run tests'
        run: bundle exec rubocop

  Security-Check:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Setup Ruby and install gems'
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: 'Run Breakman'
        run: bundle exec brakeman

  build:
    runs-on: ubuntu-latest
    needs: [RSpec, Linter, Security-Check]

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: 'AWS ECR Login'
        uses: aws-actions/amazon-ecr-login@v1

      - name: 'Build, tag and push image to amazon ECR'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: docker_rails_api_sample
          IMAGE_TAG: rails_api_demo_image
        run: |
          docker build . -f docker/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
